/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package hopitalpharmacie;

import static com.sun.tools.attach.VirtualMachine.list;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import static java.nio.file.Files.list;
import static java.util.Collections.list;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author sio1
 */
public class JDProduits extends javax.swing.JDialog {

    /**
     * Creates new form listeProduit
     */
    Produit leProduit;   
    String action;
    private JDUnPdt uneListe;
    
    
    public JDProduits(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        DefaultListModel listModel = new DefaultListModel();
        for(Produit unProduit:Passerelle.donnerTousLesProduits()){
            listModel.addElement(unProduit);
        }
        listeProduits.setModel(listModel);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listeProduits = new javax.swing.JList<>();
        btnListeProduitAjouter = new javax.swing.JButton();
        btnListeProduitFermer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        listeProduits.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listeProduits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeProduitsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listeProduits);

        btnListeProduitAjouter.setText("Ajouter un Produit");
        btnListeProduitAjouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListeProduitAjouterMouseClicked(evt);
            }
        });

        btnListeProduitFermer.setText("Fermer");
        btnListeProduitFermer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListeProduitFermerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 981, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnListeProduitAjouter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListeProduitFermer)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListeProduitAjouter)
                    .addComponent(btnListeProduitFermer))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListeProduitAjouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListeProduitAjouterMouseClicked
        uneListe = new JDUnPdt(null,true,null,"ajouter");
        uneListe.setVisible(true);
    }//GEN-LAST:event_btnListeProduitAjouterMouseClicked

    private void btnListeProduitFermerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListeProduitFermerMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnListeProduitFermerMouseClicked

    private void listeProduitsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeProduitsMouseClicked
        int choix = listeProduits.getSelectedIndex();
        Object machin = listeProduits.getModel().getElementAt(choix);
        leProduit = (Produit) machin;
        uneListe = new JDUnPdt(null,true,leProduit,"modifier");
        uneListe.setVisible(true);
        
        
    }//GEN-LAST:event_listeProduitsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDProduits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDProduits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDProduits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDProduits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDProduits dialog = new JDProduits(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListeProduitAjouter;
    private javax.swing.JButton btnListeProduitFermer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listeProduits;
    // End of variables declaration//GEN-END:variables
}
